Given 2 numpy arrays return unique elements
PEC-CSS/graveyard pull request #101
Opened 2023-03-02 16:46 UTC by aadityavvij

Resolved Given 2 numpy arrays return unique elements #52

2023-03-02 20:12 UTC, ken1000minus7 commented
@aadityavvij you should make a separate branch before starting work on an issue, as now your pr has changes for both the issues, u need to remove the files that are not related to this issue

2023-03-03 05:43 UTC, uttammittal02 requested changes
Try to do this using `np.unique()` without a loop

2023-03-03 07:29 UTC, aadityavvij commented
Tried a lot, but i am getting wrong answer with np.unique() if i put repeated elements in array1

2023-03-03 11:05 UTC, uttammittal02 commented
> Tried a lot sir, but I am getting the wrong answer with np.unique() if I put repeated elements in array1 @uttammittal02

You have 2 np arrays and you can make a 2d array consisting of both of them and then use `np.unique()` on that 2d array to get the required result

2023-03-03 15:24 UTC, aadityavvij commented
sir, but in 2d arrays np.unique() is giving repeated rows or columns and not giving repeated elements in rows or columns

2023-03-05 08:55 UTC, ken1000minus7 commented
You can remove `np.unique()` now since it would remove repeated elements of the ans array, the rest code's fine @aadityavvij

2023-03-06 04:51 UTC, uttammittal02 approved these changes
Lgtm

2023-03-06 04:51 UTC, uttammittal02 commented on ml/Given 2 numpy arrays return unique elements.py
> +    print(np.unique(array1[np.where(array1!=array2)]))
Seems good
Also, you can do this in one more way
`print(array1[array1 == array2])`

2023-03-06 04:54 UTC, uttammittal02 commented on ml/Given 2 numpy arrays return unique elements.py
> +    print(np.unique(array1[np.where(array1!=array2)]))
One more method you can use to do this is `print(array1[array1 != array2])`

2023-03-06 07:40 UTC, merged