Largest number #136
PEC-CSS/graveyard pull request #139
Opened 2023-03-04 05:40 UTC by ItsPranavz

#136 Couldn't find a feasible way to convert vector to string without getting 100+ errors but it's getting the job done without needing to print an integer.

2023-03-04 08:18 UTC, Ishwarendra commented
Your logic is incorrect @ItsPranavz. As mentioned by @iamakashrout [here](https://github.com/PEC-CSS/graveyard/issues/136#issuecomment-1454510655), your code doesn't even pass the samples.

2023-03-07 20:16 UTC, ken1000minus7 commented
@ItsPranavz any updates?

2023-03-08 02:51 UTC, ItsPranavz commented
> @ItsPranavz any updates?

I had implemented provision to first break the inputs into digits and then add to vector and also convert the vector to string using to_string and a for loop. However soon after celebrating I realized vector was the wrong data type to store in because you can't push back to the same integer when the last int is same as current int so now I have to rethink everything. 😭

2023-03-08 12:27 UTC, ItsPranavz commented
Please review the code now. I shifted back to python after trying my best with cpp but I think there is much to learn still. I tried to use vector but failed and then also tried to store the number of unique digits in an array of length 10 as a frequency distribution at corresponding indices but failed. I guess I need to learn more about data structures in cpp before I try my hand at this.

2023-03-08 12:28 UTC, ItsPranavz commented
Python it is for now!

2023-03-08 12:56 UTC, Ishwarendra commented
@ItsPranavz incorrect logic. Check the case below
```
1
23
```

2023-03-08 13:06 UTC, ken1000minus7 commented
@ItsPranavz Your code doesn't pass the 2nd sample, reread the ques you are mixing digits of different numbers

2023-03-08 13:08 UTC, ItsPranavz commented
> @ItsPranavz Your code doesn't pass the 2nd sample, reread the ques you are mixing digits of different numbers

Yes, I am understanding my error now I misunderstood the statement the whole time. I am sorry for bothering you again and again. I will fix it for sure this time.

2023-03-08 14:20 UTC, ItsPranavz commented
Ok, it has to work this time. I created a score called yield score that tells the relative yield of placing a number of any length calculated as that number divided by the largest number of same length and then sort the samples in decreasing order of this yield score and display in order.

2023-03-09 19:10 UTC, Ishwarendra requested changes

2023-03-09 19:10 UTC, Ishwarendra commented on cp/largest-number.py
> +print(yield_map(inp))
```suggestion
```

2023-03-09 19:22 UTC, Ishwarendra commented
@ItsPranavz Still incorrect. Check the case below:
```
Input
923 83 8 698 667

Correct Output: (Added space so you can see each number)
923 83 8 698 667 

Your output: 
923883698667
```

2023-03-10 04:15 UTC, ItsPranavz commented
Made the change.

2023-03-10 05:52 UTC, merged