Longest substring
PEC-CSS/graveyard pull request #187
Opened 2023-03-06 08:28 UTC by ragss69

2023-03-07 11:58 UTC, ragss69 commented
Please review my PR so I can be assigned more issues...

2023-03-07 16:32 UTC, Ishwarendra commented
@ragss69 mention issue number in commit.

2023-03-07 16:42 UTC, ragss69 commented
> @ragss69 mention issue number in commit.

Done

2023-03-07 18:22 UTC, ken1000minus7 requested changes
Your logic is incorrect
```
ababab
1
```
For this testcase answer is 1, but your code gives 3

2023-03-07 18:22 UTC, ken1000minus7 commented on cp/longest substring.py
> +if (1 <= len(s) <= 10**4) and (1 <= k <= 26):
You don't need this if condition, the constraints mean that u can assume that user's input iwll be in this range, so there's no need to check if the input lies in this range

2023-03-07 19:01 UTC, ragss69 commented
> Your logic is incorrect
> 
> ```
> ababab
> 1
> ```
> 
> For this testcase answer is 1, but your code gives 3

Sir  we have to find the length of the longest substring and according to the test case,  substring of 'ababab',  having one distinct character will be 'aaa' or 'bbb'and its length is 3.....please correct me if I am wrong or misunderstood the question.

2023-03-07 20:08 UTC, ken1000minus7 commented
by definition, a substring is a **contiguous** sequence of characters within a string, so in `ababab` in `ab` is a substring as it is the string formed from the sequence of characters from index 0 to 1 while `aaa` is not a substring as no 3 a's occur together in the string

2023-03-08 11:17 UTC, ragss69 commented
> by definition, a substring is a **contiguous** sequence of characters within a string, so in `ababab` in `ab` is a substring as it is the string formed from the sequence of characters from index 0 to 1 while `aaa` is not a substring as no 3 a's occur together in the string

Understood sir, I have now made the required changes...... please check

2023-03-08 12:48 UTC, ken1000minus7 commented
```
aba
3
```
Answer would be 3, but ur code gives runtime error, the questions says that length of the substring should be at most k, not exactly k

2023-03-08 15:49 UTC, ragss69 commented
> ```
> aba
> 3
> ```
> 
> Answer would be 3, but ur code gives runtime error, the questions says that no of unique characters should be at most k, not exactly k

Changed "==k "to "<=k", hope that would fix the problem...

2023-03-08 21:00 UTC, ken1000minus7 approved these changes
Lgtm

2023-03-08 21:00 UTC, merged