Ageing
PEC-CSS/graveyard pull request #193
Opened 2023-03-06 16:29 UTC by krittika2004

Resolved issue #72

2023-03-06 18:00 UTC, ken1000minus7 requested changes
Hey @krittika2004 your code is correct, but I have mentioned a change below

2023-03-06 18:00 UTC, ken1000minus7 commented on cp/ageing.cpp
> +    if(T>=1 && T<=25)
The constraints given the question $1 <= T <= 25$ mean that T will always be given in this range, so you don't have to check that T lies in this range, instead you have to assume that user will give a T that lies in this range, later as you'll solve more dsa problems you'll understand more about the importance of constraints because for example if the constraints show that the input can be very large then you'll have to think of efficient algorithm

So u can remove this if condition

2023-03-07 13:13 UTC, ken1000minus7 commented
Looks good, just delete the .exe file

2023-03-07 17:18 UTC, krittika2004 commented
> Looks good, just delete the .exe file

How do i delete pls tell

2023-03-07 17:38 UTC, harshjohar commented
just delete the file in your editor and commit again @krittika2004

2023-03-07 18:13 UTC, ken1000minus7 commented
The file's still there @krittika2004

2023-03-08 11:58 UTC, harshjohar approved these changes
lgtm

2023-03-08 11:58 UTC, merged