Check If N and Its Double Exist #20
PEC-CSS/graveyard pull request #39
Opened 2023-02-28 20:27 UTC by Prakul06

Resolved Issue #20

2023-03-01 16:15 UTC, ken1000minus7 requested changes
Hey @Prakul06 your code is correct but there r a few things I would like to mention, in a question constraints refer to the range in which input will be given, so actually u do not need to check if the input follows the constraints, u can assume that the input will be in the given constraints, as u will start solving dsa problems you'll see that based on constraints, our solution can change as for example if the constraints say that the input can be very large, it means that we have to think of an optimized solution 

The code you have written is correct but there also exists a more optimized approach which u can look up if u want to but for now just take care of the points I will be mentioning below

2023-03-01 16:15 UTC, ken1000minus7 commented on misc/N and its Double.c
> +    printf("Enter N=");
In questions like these we do not give input prompt asking for input, so u can remove all the input prompts everywhere and assume that the user knows what has to be given

2023-03-01 16:15 UTC, ken1000minus7 commented on misc/N and its Double.c
> +    if(N>=2 & N<=500)
As I mentioned above, u can assume that `N` lies in the range given in constraints so u do not need this condition

2023-03-01 16:15 UTC, ken1000minus7 commented on misc/N and its Double.c
> +            }
Similarly u can remove these elf conditions as well

2023-03-01 16:15 UTC, ken1000minus7 commented on misc/N and its Double.c
> +                        printf("True");
You should prefer ending your ans with a new line character i.e. `\n`, make this change everywhere

2023-03-02 19:00 UTC, Prakul06 commented
Changes Done!!

2023-03-02 20:02 UTC, ken1000minus7 commented
You haven't taken input for n, and the input prompt for array elements is still there, when I said you need to remove the input prompt i meant the message asking for input and not the input itself

2023-03-02 20:45 UTC, ken1000minus7 approved these changes
Lgtm

2023-03-02 20:46 UTC, merged